#!/usr/bin/env bash

if [[ ! -f ".gitignore" ]]; then
    echo "You need to run this from a directory with .gitignore present."
    exit 222
fi

find -- * -type l -not -exec grep -q "^{}$" .gitignore \; -print >> .gitignore_new
# mv .gitignore_new .gitignore
